---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__(<p>__start__</p>)
	read_and_extract(read_and_extract)
	find_relevant_rules(find_relevant_rules)
	reason_about_compliance(reason_about_compliance)
	check_for_anomalies(check_for_anomalies)
	decide_action(decide_action)
	act_or_escalate(act_or_escalate)
	explain_and_record(explain_and_record)
	generate_report(generate_report)
	learn_from_feedback(learn_from_feedback)
	__end__(<p>__end__</p>)
	__start__ --> read_and_extract;
	act_or_escalate --> explain_and_record;
	check_for_anomalies --> decide_action;
	decide_action --> act_or_escalate;
	explain_and_record --> generate_report;
	find_relevant_rules --> reason_about_compliance;
	read_and_extract --> find_relevant_rules;
	reason_about_compliance --> check_for_anomalies;
	generate_report --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
